/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface RefreshTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  replaced_by: string | null;
  revoked: Generated<boolean>;
  token: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified_at: Timestamp | null;
  id: Generated<string>;
  name: string;
  password: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  refresh_tokens: RefreshTokens;
  users: Users;
}
